name: hello-github

on:
  push:
    branches:
      - master

jobs:
  Docker:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git - Get Sources
        uses: actions/checkout@master

      - name: Docker - Build
        run: docker build . --file Dockerfile --tag hello-github

      - name: Docker - test
        run: docker run --rm hello-github

      - name: Docker - Publish
        run: |
          docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker tag hello-github docker.pkg.github.com/benguichard/hello-github/hello-github:latest 
          docker push docker.pkg.github.com/benguichard/hello-github/hello-github:latest
