name: hello-github

on:
  push:
    branches:
      - master

jobs:
  Docker:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git - Get Sources
        uses: actions/checkout@master

      - name: Docker - Build
        run: docker build . --file Dockerfile --tag hello-github

      - name: Docker - test
        run: docker run --rm hello-github

      - name: Docker - Publish
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: benguichard/hello-github
          auto_tag: true
