name: hello-github

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git - Get Sources
        uses: actions/checkout@master

      - name: Docker - Build
        run: docker build . --file Dockerfile --tag hello-github

      - name: Docker - test
        run: docker run --rm hello-github
  #Publish:
  #  name: Publish on Github Package Registry
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Docker - Publish
  #      uses: jerray/publish-docker-action@master
  #      with:
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}
  #        registry: docker.pkg.github.com
  #        repository: $GITHUB_REPOSITORY
  #        auto_tag: true
